### ISSUE TITLE
Landing page doesn't load for the provided list of DMP IDs

### ISSUE THREAD

**Issue by jupiter007** [CDLUC3/dmsp_api_prototype#3]
While working on issue [#631](https://github.com/CDLUC3/dmptool/issues/631), I noticed that the landing page didn't load for the following DMPs. I saw different errors in the console, such as "Cannot read properties of undefined (reading 'affiliation_id')". 

We need to go through the list and fix the issues preventing the landing pages from loading.

https://doi.org/10.48321/D1H010
https://doi.org/10.48321/D1MS3M
https://doi.org/10.48321/D1G01P
https://doi.org/10.48321/D12A9C44eb
https://doi.org/10.48321/D1C885
https://doi.org/10.48321/D1KS39
https://doi.org/10.48321/D13S3Z

**Comment by briri** [comment]
I tried to load https://doi.org/10.48321/D1H010 and then went in to check the CloudWatch logs for the API Lambda, `GetDmp`, that services the landing pages and there are no errors. It successfully returned the JSON for the DOI. This can be confirmed by calling the API directly: https://api.dmphub.uc3prd.cdlib.net/dmps/10.48321/D1H010
 
 The console shows a couple of errors: 
 - `TypeError: Cannot read properties of undefined (reading 'affiliation_id') at Me (contributors.js:35:13)` 
 - `TypeError: Cannot read properties of undefined (reading 'toString') at works.js:7:26`
 
 Issue is likely just a missing null check.

**Comment by briri** [comment]
Bug resurfaced while investigating another issue, so I patched
